[project]
name = "deploy-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Felipe Vadao", email = "felipeconceicaopc@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "agno>=3.0.0",
    "anthropic>=1.0.0",
    "chromadb>=1.5.9",
    "fastapi>=0.141.1",
    "fastembed>=0.8.0",
    "openai>=3.3.1",
    "pypdf>=6.16.2",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.62.0",
    "uvicorn>=0.52.4",
    "watchdog>=6.0.0",
]

[project.scripts]
deploy-agno = "deploy_agno:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "Deploy_Agno1.0",
]
